### ISSUE TITLE
Hardcoded team project @ GetCycleTimeAndThroughputCommand

### ISSUE THREAD

**Issue by leonmondria** [benday-inc/azdoutil#11]
Just found your blog & util, would love to try the forecasting & simulations but I get auth error.
I suspect this line to be the problem because of the hardcoded team?

`https://github.com/benday-inc/azdoutil/blob/2f61b784321b95486e598dd347abdd55396a20fc/Benday.AzureDevOpsUtil.Api/GetCycleTimeAndThroughputCommand.cs#L148`

**Comment by benday** [comment]
Hey @leonmondria --

Can you post the auth error that you're getting?  

In the meantime, I'm going to work on adding a teams argument to the flow metric calculations.
